# Atividade Prática - Exercício 5
#### Valor : 10 pontos

In [8]:
import numpy as np

1) Solicite ao usuário que informe a quantidade de linhas (n) e colunas (m) e crie um ndarray nxm com valores aleatórios.

In [59]:
n = int(input('Digite a dimensão n da matriz: '))
m = int(input('Digite a dimensão m da matriz: '))

x = np.matrix(np.arange(n*m).reshape((n, m)))
print(x)

Digite a dimensão n da matriz: 5
Digite a dimensão m da matriz: 5
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


2) Retorne a média dos valores de cada uma das n linhas

In [64]:
print(x.mean(1))

[[ 2.]
 [ 7.]
 [12.]
 [17.]
 [22.]]


3) Retorne a mediana dos valores das m colunas

In [52]:
x = np.array([x])
median=np.median(x)
print(f'A mediana dos valores das m colunas é {median}.')

A mediana dos valores das m colunas é 12.0.


4) Retorne o valor máximo de todo array

In [51]:
arr = np.array([x])
maxElement = np.amax(arr)
print(f'O máximo valor do array é {maxElement}.')

O máximo valor do array é 24.


5) Faça uma função que receba um ndarray de valores inteiros e retorne um ndarray de mesma dimensão, onde os valores negativos serão substituídos por True e os valores positivos por False.

In [66]:
print(np.isinf(arr))

[[[[[False False False False False]
    [False False False False False]
    [False False False False False]
    [False False False False False]
    [False False False False False]]]]]
